class Services {
 static String baseEndPoint = "https://home-finder-back-end-i7ca.onrender.com/api/v1/";
 static String resendVerificationEndPoint = "auth/resend-code/65ef8459c2bd7a5646b05034"; //Post
 static String verificationCodeEndPoint = "auth/verification/65ef8459c2bd7a5646b05034";//post
 static String shopEndPoint = "shop"; //Post
 static String productEndPoint = "item"; //Post
  static String productPagenationEndPoint = "item_pagination"; //Post
 static String mainCategoryDataProductEndPoint = "ctg/view"; //Post
 static String shopDetailedEndPoint = "shop/view"; //Post
 static String productDetailedEndPoint = "item/view"; //Post
 static String advertismentEndPoint = "slider"; //Post
 static String advertismentHasBeenUsedEndPoint = "slider_click"; //Post
 static String linksEndPoint = "social"; //Post
 static String signingUpEndPoint = "auth/signup"; //Post
 static String completeSigningUpEndPoint = "auth/complete-signup";
 static String signingInEndPoint = "auth/login"; //Post
 static String editingMemberDataEndPoint = "member/edit"; //Post
 static String editingMemberPasswordEndPoint = "member/change_password"; //Post
 static String getUserDataEndPoint = "member"; //Post
 static String getFavoriteShopDataEndPoint = "sfavorite"; //Post
 static String getShopIsInFavoriteOrNotEndPoint = "sfavorite/check"; //Post
 static String addOrRemoveShopToFavoriteEndPoint = "sfavorite/new"; //Post
 static String deleteUserAccountEndPoint = "member_delete"; //Post
 static String orderingProductEndPoint = "item/form"; //Post
 static String getFavoriteProductDataEndPoint = "ifavorite"; //Post
 static String getProductsInFavoriteOrNotEndPoint = "ifavorite/check"; //Post
 static String addOrRemoveProductToFavoriteEndPoint = "ifavorite/new"; //Post
 static String privacyPolicyEndPoint = "policy"; //post
 static String termsAndConditionEndPoint = "terms"; //post
 static String sendingReportEndPoint = "report";//post
 static String getOrdersHistoryEndPoint = "order/history";//post
 static String advancedSearchEndPoint = "search";//post
 static String advancedSearchPaginationEndPoint = "search_pagination";//post
 static String statsEndPoint = "order/new";//post
 static String addingCommentEndPoint = "review/new";//post
 static String getCommentEndPoint = "review";//post
 static String forgetPasswordEndPoint = "auth/forgot-pass";//post
 static String getUserChatListEndPoint = "chat//get-conversations";//get
  static String getUserConversationEndPoint = "chat/get-conversation/";//get
 static String searchUserChatListEndPoint = "chat/search-users?";//get
 static String sendMessageEndPoint = "chat/send/";//post
 static String editMessageEndPoint = "chat/edit-message/";//patch
 static String deleteMessageEndPoint = "chat/delete-message/";//delete
 static String deleteConversationEndPoint = "chat/delete-conversation/";//delete
 static String resendVerificationForgetEndPoint = "auth/resend-pass-otp/"; //Post
 static String verificationCodeForgetEndPoint = "auth/verify-pass-otp/";//post
 static String addFavEndPoint = "user/favorites/add/"; //get
 static String deleteFavEndPoint = "user/favorites/delete/"; //delete
 static String deleteAllFavEndPoint = "user/favorites/delete"; //delete
 static String signOutEndPoint = "auth/logout"; //get
 static String resetPasswordEndPoint = "auth/reset-pass/";//patch
 static String deleteAccountEndPoint = "user/delete-user";//delete
 static String uploadImageEndPoint = "user/upload-image";//post
 static String changePasswordEndPoint = "user/change-password";//patch
 static String getUserEndPoint = "user/get-user";//get
 static String updateUserEndPoint = "user/update-user";//patch
 static String deleteAccountPhotoEndPoint = "user/delete-profile-picture";//delete
 static String createResidence = "residence/create"; //Post
 static String firstCompleteEndPoint = "residence/complete/1st/";
 static String secondCompleteEndPoint = "residence/complete/2nd/";
 static String thirdCompleteEndPoint = "residence/complete/3rd/";
 static String fourthCompleteEndPoint = "residence/complete/4th/";
 static String updateResidence = "residence/update"; //patch
 static String firstUpdateEndPoint = "residence/update/1st/";
 static String secondUpdateEndPoint = "residence/update/2nd/";
 static String thirdUpdateEndPoint = "residence/update/3rd/";
 static String fourthUpdateEndPoint = "residence/update/4th/";
 static String deleteOneResidenceEndPoint = "residence/delete/";//delete
 static String getSoldForProfileEndPoint = "residence/sold";//get
 static String getResidencesPhotosEndPoint = "residence/images/";//get
 static String getAllReviewsOfOneResidenceEndPoint = "review/get/";//get
 static String addReviewEndPoint = "review/";//post
}
